//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bromotestPT4
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BromoAirlinesEntities : DbContext
    {
        public BromoAirlinesEntities()
            : base("name=BromoAirlinesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Akun> Akuns { get; set; }
        public virtual DbSet<Bandara> Bandaras { get; set; }
        public virtual DbSet<JadwalPenerbangan> JadwalPenerbangans { get; set; }
        public virtual DbSet<KodePromo> KodePromoes { get; set; }
        public virtual DbSet<Maskapai> Maskapais { get; set; }
        public virtual DbSet<Negara> Negaras { get; set; }
        public virtual DbSet<PerubahanStatusJadwalPenerbangan> PerubahanStatusJadwalPenerbangans { get; set; }
        public virtual DbSet<StatusPenerbangan> StatusPenerbangans { get; set; }
        public virtual DbSet<TransaksiDetail> TransaksiDetails { get; set; }
        public virtual DbSet<TransaksiHeader> TransaksiHeaders { get; set; }
    }
}
